config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to =>'homes#top'
  get "home/about" => "homes#about",as:"about"
  resources :books
  resources :users, only: [:show,:edit,:update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum:200 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, uniqueness: true,
                   length: { minimum:2, maximum:20 }
  validates :introduction, length: { maximum:50 }
  has_many :books,dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id) 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @books = Book.all
    @book_new = Book.new
    @user = current_user
  end
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render "/books/edit"
    end
  end
  
  def create
    @user = current_user
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = 'You have created book successfully.'
     redirect_to book_path(@book_new.id)
    else
      @books = Book.all
      render "index"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

def show
  @user = User.find(params[:id])
  @user_current = current_user
  @books = @user.books
  @book_new = Book.new
end

def index
  @user = User.all
  @user_current = current_user
  @book_new = Book.new
end

def edit
  @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
end

def update
  @user = User.find(params[:id])
    if @user.update(user_params)
  flash[:notice] = 'You have updated user successfully.'
  redirect_to user_path(@user.id)
    else
      render "/users/edit"
    end
end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>

  <div class="col-md-3">
    <h2>User info</h2>
     <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
       <tbody>
        <tr></tr>
        <tr>
         <th>name</th>
         <th class="profile-name"><%= user.name %></th>
        </tr>
        <tr>
         <th>introduction</th>
         <th class="profile-introduction"><%= user.introduction %></th>
        </tr>
       </tbody>
      </table>
      <div class="row">
       <%= link_to "",edit_user_path(user) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
      
       <%= form_with model: book_new, local:true do |f| %>
      <div class="form-group">
       <label class="form">Title</label>
        <%= f.text_field :title,class:"form-control"%>
       </div>
       <div class="form-group">
       <label class="form">Opinion</label>
        <%= f.text_field :body,class:"form-control" %>
       </div>
       <div class="form-group">
        <%= f.submit 'Create Book',class: "btn btn-success" %>
       </div>
<% end %>
   </div>

app/views/books/edit.html.erb
  <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
      <% end %>

<p id="notice"></p>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
       <label class="form">Title</label>
        <%= f.text_field :title,class:"form-control"%>
       </div>
       <div class="form-group">
       <label class="form">Opinion</label>
        <%= f.text_field :body,class:"form-control" %>
       </div>
       <div class="form-group">
        <%= f.submit 'Update Book',class: "btn btn-success" %>
       </div>
<% end %>
<span>
    <%= link_to "Show",book_path(@book.id) %>
    |
    <%= link_to "Back","/books"%>
</span>
</div>
</div>
</div>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>

  <% if @book_new.errors.any? %>
      <h3><%= @book_new.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
      <% end %>


<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'books/books', user: @user,book_new: @book_new %>

   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th col-span="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @books.each do |book| %>
      <tr>
       <td>
        <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
       </td>
       <td>
        <%= link_to book_path(book.id) do %>
          <%= book.title %>
        <% end %>
       </td>
       <td>
        <%= book.body %>
       </td>
      </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
<div class="form">Title</div>
<div><%= f.text_field :title %></div>
<div class="form">Opinion</div>
<div><%= f.text_field :opinion %></div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>

  <% if @book_new.errors.any? %>
      <h3><%= @book_new.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
      <% end %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'books/books', user: @user,book_new: @book_new %>

   <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
     <tbody>
      <tr>
       <td>
        
         <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
        
        <br>
        <%= link_to @user do %>
        <%= @user.name %>
        <% end %>
       </td>
       <td>
        <%= @book.title %>
       </td>
       <td>
        <%= @book.body %>
       </td>
       <td>
         <% if @book.user == current_user %>
         <%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success" %>
       </td>
       <td>
         <%= link_to "Destroy", book_path(@book), method: :delete,class:"btn btn-sm btn-danger" %>
         <% end %>
       </td>
      </tr>
     </tbody>
    </table>
   </div>
  </div>
 </div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
<div class="row">
<h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
<div class="row">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
 <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
 <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
 <p>
  you can share and exchange your opinions , inpressions , and emotions
 </p>
 <p>
  about various books!
 </p>
   <div class="btn-wrapper col-10 mx-auto">
     <div class="row">
      <%= link_to "Log in", new_user_session_path,class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
     </div>
     <div class="row">
      <%= link_to "Sign Up", new_user_registration_path,class: "btn btn-success btn-sm btn-block sign_up" %>
     </div>
   </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
      <span>Bookers</span>
      </a>
    <% if user_signed_in? %>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse",id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li>
        <%= link_to " Home", user_path(current_user.id) ,class: 'fas fa-home nav-link text-light' %>
      </li>
      <li>
        <%= link_to " Users", "/users" ,class: 'fas fa-users nav-link text-light'%>
      </li>
      <li>
        <%= link_to " Books", "/books",class: 'fas fa-book-open nav-link text-light'%>
      </li>
      <li>
        <%= link_to " logout", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light'%>
      </li>
    </ul>
    </div>
    <% else %>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse",id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li>
        <%= link_to " Home", "/",class: 'fas fa-home nav-link text-light' %>
      </li>
      <li>
        <%= link_to " About", "/home/about",class: 'fas fa-link nav-link text-light' %>
      </li>
      <li>
        <%= link_to " sign up", new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %>
      </li>
      <li>
        <%= link_to " login", new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-light' %>
      </li>
    </ul>
    </div>
    <% end %>
    </div>
    </nav>
    </header>
    <main>
    <% flash.each do |message_type, message| %>
    <%= message %>
    <% end %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">
     <p>CopyRight Infratop.inc</p>
      </div>
      </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_users.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>

  <div class="col-md-3">
    <h2>User info</h2>
     <%= attachment_image_tag @user_current, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
       <tbody>
        <tr></tr>
        <tr>
         <th>name</th>
         <th class="profile-name"><%= @user_current.name %></th>
        </tr>
        <tr>
         <th>introduction</th>
         <th class="introduction"><%= @user_current.introduction %></th>
        </tr>
       </tbody>
      </table>
      <div class="row">
       <%= link_to "",edit_user_path(@user_current) ,class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
       <%= form_with model: @book_new, local:true do |f| %>
      <div class="form-group">
       <label class="form">Title</label>
        <%= f.text_field :title,class:"form-control"%>
       </div>
       <div class="form-group">
       <label class="form">Opinion</label>
        <%= f.text_field :body,class:"form-control" %>
       </div>
       <div class="form-group">
        <%= f.submit 'Create Book',class: "btn btn-success" %>
       </div>
<% end %>
   </div>

app/views/users/edit.html.erb
  <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
      <% end %>

<p id="notice"></p>
<div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
    <div class="form-group">
      <label class="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name",class:"form-control"%>
    </div>
    <div class="form-group">
      <label class="inputImage">Image</label>
    <%= f.attachment_field :profile_image,class:"form-control-file"%>
    </div>
    <div class="form-group">
      <label class="inputIntroduction">Introduction</label>
    <%= f.text_field :introduction, autofocus: true, id:"introduction",class:"form-control"%>
    </div>
    <div class="form-group">
    <%= f.submit "Update User",class: "btn btn-secondary" %>
    </div>
    <% end %>
   </div>
  </div>
</div>

app/views/users/index.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">

<%= render 'users/users', user: @user %>

   <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
        <% @user.each do |user| %>
        <tr>
         <td>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
         </td>
         <td>
          <%= user.name %>
         </td>
         <td>
          <%= link_to "Show",user_path(user.id)  %>
         </td>
        </tr>
        <% end %>
      </tbody>
     </table>
   </div>
 </div>
</div>

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/c554defd4c.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">

<%= render 'books/books', user: @user,book_new: @book_new %>

   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th col-span="3"></th>
      </tr>
     </thead>
     <tbody>
      <% @books.each do |book| %>
      <tr>
       <td>
        <%= link_to user_path(@user) do %>
         <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
       </td>
       <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
       </td>
       <td>
        <%= book.body %>
       </td>
      </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>